-- ⚡ QUICK FIX: Run this in Supabase SQL Editor NOW
-- This fixes the "null value in column id" errors

-- NOTE: Chat and Knowledge tables use TEXT ids (generated by nanoid)
-- Only Message table uses auto-increment integers

-- Fix auto-increment for Message table (it's the only one that needs it)
CREATE SEQUENCE IF NOT EXISTS "Message_id_seq";
ALTER TABLE "Message" ALTER COLUMN "id" SET DEFAULT nextval('"Message_id_seq"');
SELECT setval('"Message_id_seq"', COALESCE((SELECT MAX(id) FROM "Message"), 0) + 1, false);

-- Add deviceId columns (Chat and Knowledge need these)
ALTER TABLE "Chat" ADD COLUMN IF NOT EXISTS "deviceId" TEXT;
ALTER TABLE "Knowledge" ADD COLUMN IF NOT EXISTS "deviceId" TEXT;

-- Create indexes for faster queries
CREATE INDEX IF NOT EXISTS "Chat_deviceId_idx" ON "Chat"("deviceId");
CREATE INDEX IF NOT EXISTS "Knowledge_deviceId_idx" ON "Knowledge"("deviceId");

-- Set existing data to legacy device
UPDATE "Chat" SET "deviceId" = 'legacy_device' WHERE "deviceId" IS NULL;
UPDATE "Knowledge" SET "deviceId" = 'legacy_device' WHERE "deviceId" IS NULL;

-- ✅ Done! Refresh your app and try again.
-- Chat and Knowledge IDs are generated by nanoid() in the code, not by database sequences.
